###################################################################################################
## PACKAGE: Unavailable Entities Sensor v2.0
## DESCRIPTION: Count and list entities with a state of unknown or unavailable
## REQUIREMENTS: Home Assistant v2022.5
## USAGE: https://github.com/jazzyisj/unavailable-entities-sensor/blob/main/README.md
###################################################################################################

# REQUIRED - This is the template sensor
template:
  - sensor:
      - name: "Unavailable Entities"
        unique_id: unavailable_entities
        icon: "{{ iif(states(this.entity_id)|int(-1) > 0, 'mdi:alert-circle', 'mdi:check-circle') }}"
        state_class: measurement
        state: >
          {% set entities = state_attr('group.unavailable_entities', 'entity_id') %}
          {{ entities | count if entities != none else -1 }}

# REQUIRED - Add individual entities to ignore to this group.
group:
  ignored_entities:
    entities: []

# REQUIRED - This is required to create and update the monitored entities group. Sensor updates once every minute.
automation:
  - id: update_unavailable_entities_group
    alias: "Update Unavailable Entities Group"
    description: "Update unavailable entities group."
    mode: single
    max_exceeded: silent
    trigger:
      - trigger: homeassistant
        id: startup
        event: start

      - trigger: event
        event_type: call_service
        event_data:
          domain: group
          service: reload

      - trigger: time_pattern
        minutes: "/1"
    action:
      # IMPORTANT - This is the template to edit to exclude entities with filters.
      - action: group.set
        data:
          object_id: unavailable_entities
          entities: >
            {{ states
                | selectattr('state', 'in', ['unknown', 'unavailable'])
                | rejectattr('domain', 'in', ['button', 'conversation', 'event', 'group', 'image',
                  'input_button', 'input_text', 'remote', 'tts', 'scene', 'stt'])
                | rejectattr('entity_id', 'in', state_attr('group.ignored_entities', 'entity_id'))
                | map(attribute='entity_id') | list | sort }}

  # OPTIONAL - Example automation to demonstrate how you can utilize this sensor, see example folder for more.
  - id: unavailable_entities_notification
    alias: "Unavailable Entities Notification"
    description: "Create persistent notification if unavailable entities, dismiss if none."
    mode: restart
    trigger:
      - trigger: state
        entity_id: group.unavailable_entities
        attribute: entity_id
        to: ~
        for: 5 # prevent blank notifications
    condition:
      - condition: template
        alias: "Sensor state is a valid numerical value"
        value_template: "{{ is_number(states('sensor.unavailable_entities')) }}"
    action:
      - if:
          - condition: numeric_state
            entity_id: sensor.unavailable_entities
            below: 1
        then:
          - action: persistent_notification.dismiss
            data:
              notification_id: unavailable_entities
        else:
          - action: persistent_notification.create
            data:
              notification_id: unavailable_entities
              title: "Unavailable Entities"
              message: "{{ state_attr('group.unavailable_entities', 'entity_id') | join('\n') }}"

